language: python

python:
  - "2.7"

install: "pip install -r requirements.txt"

before_script: echo 'export PYTHONPATH=$PYTHONPATH:/home/travis/build/johncoleman83/mini-tweet-bot' >> .bashrc

script: python app.py